---
- hosts: localhost
  roles:
    - common
    - docker
    - workstation
    - go-dev
    - k8s-dev
    - protobuf-dev
  pre_tasks:
    - ansible.builtin.include_vars:
        file: local_vars.yml
        hash_behaviour: merge
      when: "([playbook_dir, 'local_vars.yml'] | path_join) is exists"
