---
- name: Setup ZSH
  hosts: localhost
  tasks:
  - name: Install ZSH package
    become: yes
    ansible.builtin.package:
      name: zsh
      state: present
  - name: Use ZSH for current user
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh
  - name: Copy ZSH config
    ansible.builtin.copy:
      src: files/zshrc
      dest: "{{ ansible_user_dir }}/.zshrc"

- name: Setup git
  hosts: localhost
  tasks:
  - name: Install git package
    become: yes
    ansible.builtin.package:
      name: git
  - name: Copy .gitconfig
    ansible.builtin.copy:
      src: files/gitconfig
      dest: "{{ ansible_user_dir}}/.gitconfig"
  - name: Copy .gitignore
    ansible.builtin.copy:
      src: files/gitignore
      dest: "{{ ansible_user_dir}}/.gitignore"

- name: Setup neovim
  hosts: localhost
  tasks:
  - name: Install packages
    become: yes
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
    - neovim
    - ripgrep
    - fd
  - name: Fetch neovim configuration
    ansible.builtin.git:
      repo: https://github.com/boogie-byte/kickstart.nvim.git
      dest: "{{ ansible_user_dir}}/.config/nvim"

- name: Docker
  hosts: localhost
  tasks:
  - name: Install docker package
    become: yes
    ansible.builtin.package:
      name: docker
  - name: Enable docker service
    become: yes
    ansible.builtin.service:
      name: docker
      enabled: yes
      state: started
  - name: Add user to docker group
    become: yes
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"  
      groups: docker
      append: yes

- name: Golang dev environment
  hosts: localhost
  tasks:
  - name: Install packages
    become: yes
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
    - go
    - golangci-lint

- name: Kubernetes tools
  hosts: localhost
  tasks:
  - name: Install packages
    become: yes
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
    - kubernetes-client # kubectl
    - kustomize
    - argocd-cli
    - kubeseal

- name: Install basic packages
  hosts: localhost
  tasks:
  - name: Install packages
    become: yes
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
    - wget
    - gcc
    - unzip
    - python3
    - perl
    - make
    - zig
    - htop
    - less
    - jq 
    - whois
