---
ssh_hosts:
  '*':
    ForwardAgent: yes

git:
  ignores:
  - '*~'
  - '*.swp'
  - '*.swo'
  - '*.pyc'
  - '*.pyo'
  - '*.sublime-project'
  - '*.sublime-workspace'
  - '*.code-workspace'
  config:
    user:
      name: Sergey Vinogradov
      useConfigOnly: "true"
    push:
      default: simple
    alias:
      co: checkout
      ci: commit
      st: status -s
      br: branch --sort=-committerdate
      hist: log --graph --pretty=format:\"[%h] %an %ad%d%n%s%n\" --date=local
    color:
      ui: auto
    init:
      defaultBranch: main
    pull:
      rebase: true
