---
- name: Install OpenSSH
  become: yes
  package:
    name: "{{ item }}"
  loop:
  - openssh-clients
- name: Create OpenSSH client config dir
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0700"
- name: Configure OpenSSH client
  template:
    src: templates/ssh_config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"

- name: Install git package
  become: yes
  package:
    name: git
- name: Create git config dir
  file:
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory
- name: Copy .gitconfig
  template:
    src: templates/gitconfig.j2
    dest: "{{ ansible_user_dir}}/.config/git/config"
- name: Copy .gitignore
  template:
    src: templates/gitignore.j2
    dest: "{{ ansible_user_dir}}/.config/git/ignore"

- name: Install neovim packages
  become: yes
  package:
    name: "{{ item }}"
  loop:
  - neovim
  - ripgrep
  - fd
- name: Fetch neovim configuration
  git:
    repo: git@github.com:boogie-byte/kickstart.nvim.git
    dest: "{{ ansible_user_dir}}/.config/nvim"

- name: Install golang dev packages
  become: yes
  package:
    name: "{{ item }}"
  loop:
  - go
  - golangci-lint
- name: Create go config dir
  file:
    path: "{{ ansible_user_dir }}/.config/go"
    state: directory
- name: Set go environment variables
  template:
    src: templates/goenv.j2
    dest: "{{ ansible_user_dir }}/.config/go/env"

- name: Install k8s tools
  become: yes
  package:
    name: "{{ item }}"
  loop:
  - kubernetes-client # kubectl
  - kustomize
  - argocd-cli
  - kubeseal

- name: Install basic packages
  become: yes
  package:
    name: "{{ item }}"
  loop:
  - gcc
  - jq 
  - make
  - perl
  - python3
  - ripgrep
  - whois
  - unzip
  - zig
