---
- name: Install OpenSSH
  become: yes
  package:
    name: openssh-client
- name: Create OpenSSH client config dir
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0700"
- name: Configure OpenSSH client
  template:
    src: templates/ssh_config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"

- name: Install git package
  become: yes
  package:
    name: git
- name: Create git config dir
  file:
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory
- name: Copy .gitconfig
  template:
    src: templates/gitconfig.j2
    dest: "{{ ansible_user_dir}}/.config/git/config"
- name: Copy .gitignore
  template:
    src: templates/gitignore.j2
    dest: "{{ ansible_user_dir}}/.config/git/ignore"

- name: Create AppImage directory
  become: yes
  file:
    path: /opt/appimages
    state: directory
- name: Add AppImage directory to $PATH
  copy:
    dest: "{{ ansible_user_dir }}/.zshrc.d/appimages_path.sh"
    content: "export PATH=$PATH:/opt/appimages/"

- name: Install neovim dependencies
  become: yes
  package:
    name: "{{ item }}"
  loop:
  - libfuse2t64
  - ripgrep
  - fd-find
- name: Download neovim AppImage
  become: yes
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.10.2/nvim.appimage
    dest: /opt/appimages/nvim
    checksum: sha256:970113b5279718126b82adddf3fbed1741db7afabf8a4134635a0d75c9f2c5d8
- name: Make neovim AppImage executable
  become: yes
  file:
    path: /opt/appimages/nvim
    mode: 0755
- name: Fetch neovim configuration
  git:
    repo: git@github.com:boogie-byte/kickstart.nvim.git
    dest: "{{ ansible_user_dir}}/.config/nvim"
- name: "Make 'vim' an alias for 'nvim'"
  copy:
    dest: "{{ ansible_user_dir }}/.zshrc.d/nvim_alias.sh"
    content: |
      alias vim='nvim'
      alias vimdiff='nvim -d'

- name: Install go-migrate
  become: yes
  apt:
    deb: https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.deb

- name: Install GitLab CLI tool
  become: yes
  apt:
    deb: https://gitlab.com/gitlab-org/cli/-/releases/v1.49.0/downloads/glab_1.49.0_linux_amd64.deb

- name: Install basic packages
  become: yes
  package:
    name: "{{ item }}"
  loop:
  - gcc
  - jq 
  - make
  - perl
  - python3
  - strace
  - whois
  - unzip
