---
- name: Install ZSH
  become: yes
  package:
    name: zsh
    state: present
- name: Use ZSH for current user
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
- name: Create ZSH config
  template:
    src: templates/zshrc.j2
    dest: "{{ ansible_user_dir }}/.zshrc"
- name: Create ZSH config directory
  file:
    path: "{{ ansible_user_dir }}/.zshrc.d"
    state: directory

- name: Install basic packages
  become: yes
  package:
    name: "{{ item }}"
  loop:
  - htop
  - less
  - tree
  - wget
